apiVersion: v1
data:
  DB_PASSWORD: c29uYW1AMTIz
  DB_USER: ZHNvMjAydXNlcg==
  POSTGRES_PASSWORD: c29uYW1AMTIz
  POSTGRES_USER: ZHNvMjAydXNlcg==
kind: Secret
metadata:
  name: dso202-secret
  namespace: dso202-assignment-01
